[package]
name = "freshwall"
version = "0.1.0"
authors = ["Gerrit 'Geaz' Gazic"]

[dependencies]
toml = "0.4"
serde_derive = "^1.0.8"
serde = "^1.0.8"
reqwest = "*"
select = "*"
wallpaper = "2.0"

[profile.release]
opt-level = 3
lto = true